# fly.toml file generated for little-river-2522 on 2023-07-21T15:24:50+08:00

app = "little-river-2522"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[deploy]
  release_command = "npx sequelize db:seed:all"


[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
